### ISSUE TITLE
Targeting

### ISSUE THREAD

**Issue by melissamcewen** [mslater777x/prj-rev-bwfs-dasmoto#2]
My general rule is I first target the whole page, seeing what things I can apply there. You did a great job with that!

Then I target general HTML elements. `<h2>`, `<p>`, etc. The reason for this is because as pages grow, it's likely that they will have more of these, so it's good to have a style for them. 

Then I target exceptions with specific classes. Here in this project that's the section header font colors. 

That's just one way of doing things and I thought it's useful to explore. 

```css
/* whole page */

body {
  font-family: "Helvetica", sans-serif;
}

/* basic elements */


h1 {
  background-image: url("https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-2/pattern.jpeg");
  text-align: center;
  font-size: 100px;
  color: khaki;
}

h2 {
  font-size: 32px;
  color: white;
}

/* specific styles */


.price {
  font-weight: bold;
  color: blue;
}

#brush {
  background-color: mediumspringgreen;
}

#frame {
  background-color: lightcoral;
}

#paint {
  background-color: skyblue;
}
```
